version: '3.9'
services:
  grpc_uploader:
    build:
      context: .
    links:
      - db
    networks:
      - internal
  db:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db:/var/lib/mysql
    networks:
      - internal

volumes:
  db:
  storage:
    name: ${PROJECT_NAME}_storage
networks:
  internal:
    name: ${PROJECT_NAME}_internal
