version: '3.9'
services:
  grpc_uploader:
    image: grpc_uploader_dev
    user: "${UID}:${GID}"
    build:
      target: dev
      args:
        MIX_ENV: dev
    ports:
      - 4000:4000
    volumes:
      # Please note changing the mount-point here would require changing
      # the workspaceFolder property in .devcontainer/devcontainer.json
      - .:/opt/app
    environment:
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
# Uncomment the following lines to provision SSH keys into the container.
# Change the file path for secrets.user_ssh_key.file as needed.
#      secrets:
#      - user_ssh_key

#secrets:
#  user_ssh_key:
#    file: ~/.ssh/keyfile

